### PR TITLE
remove objectmodule

### PR DESCRIPTION
**Pull request by sequencer**
See chipsalliance/rocket-chip#2967

### CODE REVIEW

**Comment by jerryz123** [comment]
Does the JSON artefact need to be removed as well here?

**Comment by sequencer** [comment]
Thinking...
I don't think so...
I'll try it tomorrow.

**Comment by jerryz123** [comment]
@sequencer Can you update this PR? Lets merge this

**Comment by sequencer** [comment]
I totally forgot this... sry

**Pull request closed without merging**
